// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrvpxzsvynxbskahqwug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpydnB4enN2eW54YnNrYWhxd3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzQ2NjMsImV4cCI6MjA2NTYxMDY2M30.ede9J6ASS-y-CUNFZN8yc2mKApMV3vA242Cqlpco89E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);